### ISSUE TITLE
Add cathing of Runtime Exceptions with redirecting to error page

### ISSUE THREAD

**Issue by Zalesovsky** [Andersen-Java-Intesive/task-4#14]
Example:
in this place exception is throwing
https://github.com/Andersen-Java-Intesive/task-4/blob/dev/src/main/java/org/example/dao/impl/UserDaoImpl.java#L27-L29
and in this place we shoud catch exc
https://github.com/Andersen-Java-Intesive/task-4/blob/dev/src/main/java/org/example/servlets/AddUserServlet.java#L38
and redirect to error page

**Comment by Chaplain4** [comment]
done
