### ISSUE TITLE
Make filling forms and error pages more beautiful

### ISSUE THREAD

**Issue by Zalesovsky** [Andersen-Java-Intesive/task-4#34]
Make these pages more pretty
![image](https://github.com/Andersen-Java-Intesive/task-4/assets/49143456/7abffadd-e6ac-417f-9169-33c11fd9859c)
![image](https://github.com/Andersen-Java-Intesive/task-4/assets/49143456/d472f7bc-f62d-4ce2-b344-e62943ad9fe1)
![image](https://github.com/Andersen-Java-Intesive/task-4/assets/49143456/8a249d47-5b25-4be2-900e-dc862df5b64e)

**Comment by smas655** [comment]
Added some style for jsp files
