### ISSUE TITLE
Fix validation

### ISSUE THREAD

**Issue by Zalesovsky** [Andersen-Java-Intesive/task-4#38]
Combine validation rules for strings in UserDto if it possible.  

```
    @NotBlank(message = "Empty First Name field")
    @NotNull(message = "Empty First Name field")
    @NotEmpty(message = "Empty First Name field")
```

This should be 1 annotation.
With this approach, the validator throws 3 identical errors:

```
org.opentest4j.AssertionFailedError: 
Expected :First Name field is blank
Actual   :Empty First Name field Empty First Name field Empty First Name field
```

**After this, don't forget to fix the string comparison validation tests!**

Can be done via hibernate validation.

*If you simply make different messages, this will not solve the problem, since instead of 3 identical messages, 3 different messages will be thrown, which is incorrect*

This task depends on the following: https://github.com/Andersen-Java-Intesive/task-4/issues/37

**Comment by Zalesovsky** [comment]
connected with https://github.com/Andersen-Java-Intesive/task-4/issues/43

**Comment by Chaplain4** [comment]
done
