### ISSUE TITLE
Add team features

### ISSUE THREAD

**Issue by Chaplain4** [Andersen-Java-Intesive/task-4#39]
- [x] Add new field "Team". User should belong to one of two default teams
- [x] Add new command and view: teams must be split into pairs on following conditions:
1. process must be random
2. pair must consist of two Users from different teams
3. if one team is bigger than the other, everyone from smaller team must get a pair
4. if teams have equal size, everyone must get a pair

**Comment by Zalesovsky** [comment]
Add method in service 
List<Pair<User, User>> generateUserPairs (){...}
