### ISSUE TITLE
 Add validation for Team Enum

### ISSUE THREAD

**Issue by Zalesovsky** [Andersen-Java-Intesive/task-4#43]
https://github.com/Andersen-Java-Intesive/task-4/blob/e48cbfb86b5901fa62a42966d6cae2dad9230455/src/main/java/org/example/dto/UserDto.java#L37-L39

**Comment by Zalesovsky** [comment]
connected with https://github.com/Andersen-Java-Intesive/task-4/issues/38

**Comment by Chaplain4** [comment]
done
